development:
  adapter: postgresql
  encoding: unicode
  database: becart_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: becart_test
  pool: 5

cucumber:
  <<: *test
